name: Start firebase emulators

on:
    workflow_call:

jobs:
    setup:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
          - run: |
              apt-get install -y openjdk-11-jdk ca-certificates-java