name: Start firebase emulators

on:
    workflow_call:

jobs:
    setup:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
          - name: Install firebase tools with dependencies
            run: |
              sudo apt-get install openjdk-11-jdk ca-certificates-java -y
              npm install -g firebase-tools
